"""Generate a current-workspace HLS configuration without running synthesis.
The historical hls/hls_config.cfg and original project are not modified.
"""
from pathlib import Path

HERE=Path(__file__).resolve().parent
ROOT=HERE.parent
TOP=ROOT/"csnn_cpp/include/hls4csnn1d_sd/model24/cblk_sd/topclass24_sd.cpp"
SHIM=ROOT/"hls/shim/skip_host_reader.h"
JSON_INCLUDE=ROOT/"csnn_cpp/external/json/include"


def main():
    assert TOP.is_file() and SHIM.is_file() and JSON_INCLUDE.is_dir()
    top=TOP.as_posix()
    text=f'''# Current-workspace configuration; generated by make_hls_config.py.
# Run tools from the repository root. Generation does not launch HLS.
part=xc7z020clg400-1
[hls]
clock=10ns
syn.top=topFunction
syn.file={top}
syn.file_cflags={top},-std=c++17 -include "{SHIM.as_posix()}" -DJSON_HAS_FILESYSTEM=0 -DJSON_HAS_EXPERIMENTAL_FILESYSTEM=0 -I"{JSON_INCLUDE.as_posix()}"
package.output.format=ip_catalog
package.output.file={(HERE/'qcsnn_topFunction_ip.zip').as_posix()}
package.output.syn=false
'''
    (HERE/'hls_current.cfg').write_text(text,encoding='utf-8')
    print('Generated engineering_guide/hls_current.cfg for the current workspace. No synthesis started.')


if __name__=='__main__':
    main()
