// Driver for the PATCHED copy of the kernel's forward() (dump statements added, arithmetic untouched).
// usage: golden_layers <words.bin> <preds.txt> <dump.bin> [max_beats] [sums]   ("sums": only the small gate/argmax records)
// A single network object is reused across beats, like the `static` object inside the real topFunction.
#include <cstdio>
#include <cstdint>
#include <cstdlib>
#include <vector>
#include <string>
#include "gold_dump.h"
#include "qcsnn24_rrboth_sd_dump.h"      // generated by make_golden_layers.py
using namespace hls4csnn1d_cblk_sd;

int main(int argc, char** argv) {
    if (argc < 4) { std::fprintf(stderr, "usage: golden_layers <words.bin> <preds.txt> <tensors.bin|-> [max_beats]\n"); return 2; }
    FILE* f = std::fopen(argv[1], "rb");
    std::vector<int8_t> buf;
    int8_t tmp[188];
    while (std::fread(tmp, 1, 188, f) == 188) buf.insert(buf.end(), tmp, tmp + 188);
    std::fclose(f);
    size_t N = buf.size() / 188;
    if (argc > 4) { size_t m = (size_t)std::atoi(argv[4]); if (m < N) N = m; }
    const bool want_tensors = !(argc > 5 && std::string(argv[5]) == "sums");
    g_gold.tensors = want_tensors;
    FILE* o = std::fopen(argv[2], "w");
    // sums records are always wanted, so keep a sink even without tensors
    g_gold.f = std::fopen(argv[3], "wb");
    static QCSNN24_RRBOTH_SD<10> net;
    for (size_t n = 0; n < N; ++n) {
        const int8_t* b = &buf[n * 188];
        hls::stream<ap_int8_c> in, p2, p4;
        for (int k = 0; k < 180; ++k) in.write(ap_int8_c((int)b[k]));
        ap_int8_c rr1[4], rr2[4];
        for (int k = 0; k < 4; ++k) { rr1[k] = ap_int8_c((int)b[180 + k]); rr2[k] = ap_int8_c((int)b[184 + k]); }
        g_gold.stage = 0; g_gold.step = 0;
        int32_t idx = (int32_t)n;
        gold_record("beat", 4, &idx, 1);
        net.forward(in, rr1, rr2, p2, p4);
        int a = (int)p2.read(), c = (int)p4.read();
        std::fprintf(o, "%d %d\n", a, c);
    }
    std::fclose(o);
    std::fclose(g_gold.f);
    std::printf("beats: %zu\n", N);
    return 0;
}
